# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open XDMoD Application Kernel Remote Runner Module
email: ccr-xdmod-help@buffalo.edu
description: >
  Application Kernel Performance Monitoring Module of XDMoD tool is designed to
    measure quality of service as well as preemptively identify underperforming
    hardware and software by deploying customized, computationally lightweight
    "application kernels" that are run frequently (daily to several times per
    week) to continuously monitor HPC system performance and reliability from the
    application users' point of view.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://akrr.xdmod.org" # the base hostname & protocol for your site
github_username: ubccr
github_url: https://github.com/ubccr/akrr
xdmod_module_name: Application Kernel Remote Runner (AKRR)

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
            sw_version: "2.1.0"
            version: "2.1.0"
            style: "effervescence"
            tocversion: "toc"

# Build settings
markdown: kramdown
theme_subdir: "/xdmod-jekyll-theme"
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
